services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Автоматически создаётся только одна база, вторую — создаём сами

  server:
    build: .
    environment:
      IRC_CHAT_DB_URL: ${IRC_CHAT_DB_URL}
    depends_on:
      - postgres
    command: ["./build/Server"]

  dbtests:
    build: .
    environment:
      IRC_CHAT_DB_URL: ${IRC_CHAT_TEST_DB_URL}
    depends_on:
      - postgres
    command: ["/bin/sh", "-c", "sleep 5 && psql -U $POSTGRES_USER -h postgres -c 'CREATE DATABASE irc_chat_test;' || true && ./build/DbTests"]

volumes:
  pgdata:
